# Generated by Django 2.2.6 on 2020-04-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
